### ISSUE TITLE
The checksum on some archives have changed

### ISSUE THREAD

**Issue by uhthomas** [google/go-containerregistry#997] opened 2021-04-24 18:11 UTC
Hi,

It looks like the SHA256 sums of some archives have changed.

See run fail: https://github.com/uhthomas/automata/runs/2427916713

Excerpt:

```
WARNING: Download from https://api.github.com/repos/google/go-containerregistry/tarball/8a2841911ffee4f6892ca0083e89752fb46c48dd failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was cadb09cb5bcbe00688c73d716d1c9e774d6e4959abec4c425a1b995faf33e964 but wanted 60b9a600affa5667bd444019a4e218b7752d8500cfa923c1ac54ce2f88f773e2
```

This has broken projects like `rules_docker` and requires any upstreams to explicitly import and correct the package.

For example https://github.com/uhthomas/automata/commit/0d68e65e617740c10f321f1937201951b0169dd4.

As I understand, this is may be related to https://github.com/google/ko/issues/315, although I am not sure in this case.

**Comment by afbjorklund** [comment] 2021-04-26 06:26
The git attributes are causing a lot of breakage in downstream projects, we have also seen podman and cri-o

**Comment by ImJasonH** [comment] 2021-04-26 13:26
This has all the same hallmarks as https://github.com/google/ko/issues/315, I believe it's the same issue.

Changing the SHA seems to have fixed the issue (please correct me if I'm wrong), and while it shouldn't happen again AIUI we can ensure it doesn't by updating `rules_docker` to depend on a newer version of go-containerregistry that doesn't depend on the gitVersion shenanigans at all. I see [they're on 0.1.4](https://github.com/bazelbuild/rules_docker/blob/f929d80c5a4363994968248d87a892b1c2ef61d4/repositories/go_repositories.bzl#L40), which is pretty old.

**Comment by ImJasonH** [comment] 2021-04-26 13:42
https://github.com/bazelbuild/rules_docker/pull/1829

**Comment by steeve** [comment] 2021-04-26 15:27
Repeating what has been said elsewhere:
Github branch/commit tarballs are dynamically generated. Don't depend on them having a stable SHA256. If the upstream rule is not distributing built artefacts, you'll need to use git itself or something stabler.

**Comment by afbjorklund** [comment] 2021-04-26 15:40
Fortunately the git significant digits don't check _that_ often, so most just suffers the occasional breakage... :shrug: 

Nobody distributes distfiles anymore, and there are not many build systems supporting git bundles either.

**Comment by uhthomas** [comment] 2021-04-26 22:03
I'm tempted to close this issue as this should only affect upstream dependencies which rely on GitHub's archive feature.

However, I believe this repository still needs its Kubernetes dependencies updated to prevent this from happening. So, I will leave the issue open until such time.

**Comment by tobbbles** [comment] 2021-04-26 22:21
Could this at all be related to the Codecov breach that has seen many CI tools compromised potentially breaching secrets such as signing keys? 

https://about.codecov.io/security-update/

**Comment by ImJasonH** [comment] 2021-04-26 22:23
Since v0.1.4 which rules_docker was depending on, this repo split into two Go modules. The main one, the one rules_docker depends on, no longer depends on the offending Kubernetes package (only k8s codegen). The other package, k8schain, still [depends on k8s.io/client-go@v1.19.7](https://github.com/google/go-containerregistry/blob/83f4080544c8578ec02b937c2a0a4dc07198916d/pkg/authn/k8schain/go.mod#L20), which does seem to still have the nondeterminism bug.

But since the GitHub archive for the go-containerregistry repo as a whole contains the k8schain code, it seems like it's also getting included in the archive, leaking the nondeterminism out to the whole repo. So yeah, I should update k8schain to make this go away.

**Comment by ImJasonH** [comment] 2021-04-26 22:24
> Could this at all be related to the Codecov breach that has seen many CI tools compromised potentially breaching secrets such as signing keys?
> 
> https://about.codecov.io/security-update/

I don't have any indication that this issue is the cause at this time.

**Comment by tobbbles** [comment] 2021-04-26 22:58
> > Could this at all be related to the Codecov breach that has seen many CI tools compromised potentially breaching secrets such as signing keys?
> > https://about.codecov.io/security-update/
> 
> I don't have any indication that this issue is the cause at this time.

Digging a bit deeper here, and the codecov action was not checking hashes of the (compromised) bash uploader it was using under the hood https://github.com/codecov/codecov-action/issues/281. So it seems plausible that the github token from that actions workflow may have been compromised.

I have no idea what the rotation frequency of that is in actions; but looking at https://docs.github.com/en/rest/reference/repos#upload-a-release-asset it appears feasible this token could have been used to upload a new asset against a release

**Comment by imjasonh** [comment] 2021-04-28 12:14
> So it seems plausible that the github token from that actions workflow may have been compromised.

It's certainly possible, but we don't have any indication at this time that it has been, and I don't believe it's the cause of this issue at this time. If you find evidence to suggest this issue is involved, please let us know.

Aside from not depending in GitHub's dynamically generated archives in build environments intended to be reproducible (e.g., bazel, https://github.com/bazelbuild/rules_docker/pull/1829), and removing any last remaining sources of non-determinism from the archive in the first place (https://github.com/google/go-containerregistry/pull/1001), I don't think there's anything else to do at this time.

After #1001 is in, we'll cut a release.

**Comment by imjasonh** [comment] 2021-05-05 15:33
The k8schain module fix is in, the next release of ggcr should be stably generateable by GitHub archives, barring other issues.

**Closed by imjasonh** 2021-05-05 15:33 UTC
