### ISSUE TITLE
Container Registry: allow Path in URI as per RFC 3986

### ISSUE THREAD

**Issue by scodeman** [google/go-containerregistry#1089] opened 2021-07-28 04:30 UTC
`error building image: registries must be valid RFC 3986 URI authorities` issue reported at https://github.com/GoogleContainerTools/kaniko/issues/1618  seem to be related to the fact that go-containerregistry project always assume a registry is made of Host part only in the URI, but there could be a Path section to the registry URI and it should not be prevented to be specified as a registry source 

https://github.com/google/go-containerregistry/blob/596751a1747114c7f502f8a99a55891865aa2d03/pkg/name/registry.go#L100

it seems the condition `url.Host != name` is not valid for checking RFC 3986 compliance.
Is there another reason for it ?
Could it be remove so to fix issues related to it

For example in my case I use a subrepo as a `docker.io` registry mirror and have to use a registry with Path, ex: `artifactory.mycompany.io/docker-io-mirror`

**Comment by imjasonh** [comment] 2021-07-28 14:26
I think the problem is that kaniko only supports mirror registries specified at the root registry, and not root+path. They call `name.NewRegistry` [here](https://github.com/GoogleContainerTools/kaniko/blob/1d9bc175c2070680c0d2d5b1d7531ffe53d713f7/pkg/image/remote/remote.go#L60-L64) when they could call [`name.NewRepository`](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/name#NewRepository), which supports parsing not only the registry component (Host only, e.g., `my.co`) but also the repository component including path (e.g., `my.co/cache`).

Briefly browsing the kaniko code I think this should be relatively easy to fix on their end.

**Comment by imjasonh** [comment] 2021-07-28 14:35
Let's find out whether it's actually that easy to fix 😄 https://github.com/GoogleContainerTools/kaniko/pull/1707

(Closing this issue so we can continue discussion on that PR and issue)

**Closed by imjasonh** 2021-07-28 14:35 UTC

**Comment by thw0rted** [comment] 2024-08-30 19:10
Is this actually fixed?  `echo $PASS | crane auth login -u $USER registry.example.com/reponame --password-stdin` still produces

> Error: registries must be valid RFC 3986 URI authorities: registry.example.com/reponame

while a `docker login` with the same arguments works fine.
