### ISSUE TITLE
Slow uploads to quay.io

### ISSUE THREAD

**Issue by akshaymankar** [google/go-containerregistry#1193] opened 2021-11-23 10:59 UTC
I noticed that using `crane` or any other tool like [concourse-registry-image-resource](https://github.com/concourse/registry-image-resource) which uses this library to upload images to quay.io is very slow. If the same image is uploaded to docker.io, it goes much faster.  Using other tools like the docker daemon or [skopeo](https://github.com/containers/skopeo), the uploads to both docker.io and quay.io are fast. 

Here is a snippet from `crane -v copy ...` which shows the slow `PATCH` request to quay.io. The biggest layer in the image is slightly over 100 MBs and takes about 2m49s. The same layer being uploaded by skopeo takes 10s at worst. 

```
2021/11/22 13:28:25 --> PATCH https://quay.io/v2/akshay_wire/concourse-test/blobs/uploads/04efcb78-7682-49f2-aaee-c8cc268cbc4e [body redacted: omitting binary blobs from logs]
2021/11/22 13:28:25 PATCH /v2/akshay_wire/concourse-test/blobs/uploads/04efcb78-7682-49f2-aaee-c8cc268cbc4e HTTP/1.1
Host: quay.io
User-Agent: crane/0.7.0 go-containerregistry/0.7.0
Transfer-Encoding: chunked
Authorization: <redacted>
Content-Type: application/octet-stream
Accept-Encoding: gzip


2021/11/22 13:31:14 <-- 202 https://quay.io/v2/akshay_wire/concourse-test/blobs/uploads/04efcb78-7682-49f2-aaee-c8cc268cbc4e (2m49.539267251s) [body redacted: omitting binary blobs from logs]
2021/11/22 13:31:14 HTTP/2.0 202 Accepted
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Mon, 22 Nov 2021 13:31:14 GMT
Docker-Upload-Uuid: 04efcb78-7682-49f2-aaee-c8cc268cbc4e
Location: https://quay.io/v2/akshay_wire/concourse-test/blobs/uploads/04efcb78-7682-49f2-aaee-c8cc268cbc4e
Range: 0-104866282
Server: nginx/1.12.1
```

I used this dockerfile for testing: 

```Dockerfile
FROM alpine

RUN dd if=/dev/urandom of=/data bs=1024 count=$((100*1024))
```

**Comment by imjasonh** [comment] 2021-11-23 14:05
I'm not able to reproduce from my laptop:

```
$ time crane pull random.kontain.me/random:10x10000000 random.tar
crane pull random.kontain.me/random:10x10000000 random.tar  0.75s user 0.52s system 7% cpu 17.142 total

$ time crane push random.tar quay.io/imjasonh/random
2021/11/23 08:55:03 pushed blob: sha256:d9ad66c69e3452e7fd3f84e3875dabb8ca51a5e1a1ca0b778b7cf715ec73767d
2021/11/23 08:55:03 pushed blob: sha256:d79d144f8c6169fad79de8492605c36202a5913217079d02ffd17d7e4cfde9cb
2021/11/23 08:55:04 pushed blob: sha256:a998b16a0f6a0a0a1921d686f5b8aa4d54ce0c1a2d4b45fc8fb73a5292d843cc
2021/11/23 08:55:05 pushed blob: sha256:e10e79585cc43d5094a220fe5c35b541f77cb6478247f1769ffe51268070a400
2021/11/23 08:55:09 pushed blob: sha256:7f9ee9d8369a3dfa07591e743448aec66bd92b1cb0371fdcc0d8e87fd095ac83
2021/11/23 08:55:10 pushed blob: sha256:83ece294e5388e43f51291dd8b5b0477c6a08e834a477744647323e5e8b7c6e8
2021/11/23 08:55:10 pushed blob: sha256:03086df2ffc7ddb7a523dae591bb5c8b13ddc335007d62c6b2112e49707a6f42
2021/11/23 08:55:11 pushed blob: sha256:7a4c7f8d28c339eecb0656a385ba79a3e8415608793ac6d5777ef8400f93a97d
2021/11/23 08:55:15 pushed blob: sha256:73d49e6851b4345e47397514010c4bb43f9784842ca9009931ac84d0b0f8460e
2021/11/23 08:55:16 pushed blob: sha256:d9d14aa392e2361ecfe68d3c89dfaae6c3d8f81a3f46565069dfc730db378908
2021/11/23 08:55:17 pushed blob: sha256:4ebc6ff562ce6eefbcb65f4677fd907e9e3c5f54d31ec507a12b394de9a1b18f
2021/11/23 08:55:18 quay.io/imjasonh/random: digest: sha256:4aab3d89d4ebd095949134f433943beac9684a8120a423675b70eaeecf72b7c3 size: 1914
crane push random.tar quay.io/imjasonh/random  0.72s user 0.45s system 5% cpu 23.062 total
```

(With `crane`, pulling a random 100MB image took 17s, pushing took 23s)

And Skopeo:

```
$ time skopeo copy docker://random.kontain.me/random:10x10000000 docker-archive:./random.tar
Getting image source signatures
Copying blob 1b7498140795 done  
Copying blob 46a478f0efaf done  
Copying blob d72d0fba63f9 done  
Copying blob 559a902a3543 done  
Copying blob e8131dcb91d8 done  
Copying blob 3b2cf546bffd done  
Copying blob ecfc26fa6181 done  
Copying blob 0d7ac3347335 done  
Copying blob b924dbfca8ed done  
Copying blob 93fa68f66985 done  
Copying config cdfddf193a done  
Writing manifest to image destination
Storing signatures
skopeo copy docker://random.kontain.me/random:10x10000000   1.27s user 0.73s system 11% cpu 16.884 total

$ time skopeo copy docker-archive:./random.tar docker://quay.io/imjasonh/random                                                                                                                                                         (current-context is not set)
Getting image source signatures
Copying blob d6ac03e7bc2a done  
Copying blob 482b2b3cbb23 done  
Copying blob 67815c53ce6e done  
Copying blob 70e72c8d3c66 done  
Copying blob 3ef81224fd78 done  
Copying blob 4e59fd686843 done  
Copying blob af6bfb6f19a5 done  
Copying blob 47a6ce50a0de done  
Copying blob 6ce8a4eff768 done  
Copying blob d31d4553cfcd done  
Copying config cdfddf193a done  
Writing manifest to image destination
Storing signatures
skopeo copy docker-archive:./random.tar docker://quay.io/imjasonh/random  1.38s user 0.50s system 9% cpu 20.174 total
```

(With `skopeo`, pulling a random 100MB image took 16s, pushing took 20s)

If you could share a bit more logs from the push using Skopeo that could be helpful. If the registry has already seen the layer before it can sometimes avoid the push.

OTOH, `crane` might be doing something silly like decompressing and recompressing the layer before uploading, which would make things slower.

**Comment by akshaymankar** [comment] 2021-11-23 14:05
I ran a few tests and found that this issue only shows up when using HTTP2 to upload the layers. To verify this, I tried using `curl` to upload layers and the slow uploads go away if I pass `--http1.1` flag to `curl`. I am not sure whether this is a problem with the library or quay.io. But, exporting `GODEBUG=http2client=0` fixes the issue.

**Comment by imjasonh** [comment] 2021-11-23 14:24
Thanks for digging further. I'm not sure why http2 would make it slower 🤔 but it's good to know you found a workaround. I'll close this issue, feel free to ping if you see this happening again.

**Closed by imjasonh** 2021-11-23 14:24 UTC

**Comment by akshaymankar** [comment] 2021-11-23 14:47
For anyone interested, I created an issue with ProjectQuay here: https://issues.redhat.com/browse/PROJQUAY-2855

**Comment by jonjohnsonjr** [comment] 2021-11-29 18:15
Sounds a lot like https://github.com/google/go-containerregistry/pull/799
