### ISSUE TITLE
`ko` fails to pull from distroless ?

### ISSUE THREAD

**Issue by sebgoa** [google/go-containerregistry#233] opened 2018-07-16 16:31 UTC
n00b question here, trying to run my first `ko resolve` I get this:

```
$ ko resolve -f deploy.yaml 
2018/07/16 18:30:22 Using base gcr.io/distroless/base:latest for github.com/sebgoa/functions
2018/07/16 18:30:22 error processing import paths in "deploy.yaml": Get https://gcr.io/v2/token?scope=repository%3Adistroless%2Fbase%3Apull&service=gcr.io: exit status 1
```

I am in a directory that is well configured with $GOPATH and I have a simple `main.go`

**Comment by jonjohnsonjr** [comment] 2018-07-16 16:36
Do you have [`credsStore`](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) set in your `~/.docker/config.json`?

**Comment by sebgoa** [comment] 2018-07-16 16:38
yes:

```
{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.03.1-ce (darwin)"
        },
        "credsStore": "osxkeychain"
}

```

and I can pull locally:

```
$ docker pull gcr.io/distroless/base:latest
latest: Pulling from distroless/base
Digest: sha256:4b5f2a19a3cb56058265e400662df44c13352d0cb78a21f4c652b6b4d0159bb8
Status: Image is up to date for gcr.io/distroless/base:latest
```

**Comment by jonjohnsonjr** [comment] 2018-07-16 16:41
I think the issue here is that we aren't properly falling back to anonymous credentials. If you set [registry-specific cred helpers](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) instead of the global `credsStore`, I believe this issue will go away, but that's definitely a bug on our side.

**Comment by jonjohnsonjr** [comment] 2018-07-16 17:07
As a janky workaround until we fix the bug, you could do this:

In an executable script, somewhere on your path, named `docker-credential-anon`:
```
#!/bin/bash
echo '{"Username": "_token", "Secret": ""}'
```

In your `~/.docker/config.json`, add an entry under `credHelpers` for `gcr.io` called `docker-credential-anon`:
```
{
  "auths": {},
  "credHelpers": {
    "gcr.io": "anon"
  }
}
```

E.g. for you, this should look like:
```
{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "credHelpers": {
                "gcr.io": "anon"
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.03.1-ce (darwin)"
        },
        "credsStore": "osxkeychain"
}
```

That should cause us to fetch creds from `docker-credential-anon` that are essentially a NOP.

**Comment by jonjohnsonjr** [comment] 2018-07-16 17:10
@dekkagaijin any ideas?

**Comment by dekkagaijin** [comment] 2018-07-16 17:19
Weird, not off the top of my head. As you said, looks like we're sending junk creds on the token exchange and not falling back to anonymous

**Comment by sebgoa** [comment] 2018-07-16 18:30
not sure why but looks like my `config.json` was messed up. I re-ran `gcloud auth configure-docker` and things worked.


```
$ ko resolve -f deploy.yaml 
2018/07/16 20:26:58 Using base gcr.io/distroless/base:latest for github.com/sebgoa/functions
2018/07/16 20:27:00 Publishing gcr.io/cebuk-01/github.com/sebgoa/functions:latest
2018/07/16 20:27:03 mounted blob: sha256:57752e7f9593cbfb7101af994b136a369ecc8174332866622db32a264f3fbefd
2018/07/16 20:27:06 pushed blob sha256:d95b52084b1b1e69282c858521cdaaa550c6463be389cd03daaf909d99bee9cc
2018/07/16 20:27:07 pushed blob sha256:f4dfacbd82074ccb23ba92c86e90784a290afaf7fda290daa7732001dfc2257c
2018/07/16 20:27:09 gcr.io/cebuk-01/github.com/sebgoa/functions:latest: digest: sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a size: 591
2018/07/16 20:27:09 Published gcr.io/cebuk-01/github.com/sebgoa/functions@sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gcr.io/cebuk-01/github.com/sebgoa/functions@sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a
        name: hello-world
        ports:
        - containerPort: 8080
sebair: functions (master)$ docker run gcr.io/cebuk-01/github.com/sebgoa/functions@sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a
Unable to find image 'gcr.io/cebuk-01/github.com/sebgoa/functions@sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a' locally
sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a: Pulling from cebuk-01/github.com/sebgoa/functions
57752e7f9593: Already exists 
f4dfacbd8207: Pull complete 
Digest: sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a
Status: Downloaded newer image for gcr.io/cebuk-01/github.com/sebgoa/functions@sha256:05d3ddf7a232e73d15cfe01f0999fafacd4fc77f2e40073f8d7c8cbf226dbd5a
Hello
```

**Comment by ImJasonH** [comment] 2018-07-19 04:57
Closing as not reproducible. Feel free to reopen if you see this again.

**Comment by markusthoemmes** [comment] 2018-08-15 12:04
I am seeing this as well. Only logged into docker.io, manually `docker pull`ing works just fine. Error message is the same as mentioned above.

**Comment by markusthoemmes** [comment] 2018-08-15 12:11
The workaround mentioned by @jonjohnsonjr works fine FWIW.

**Comment by mattmoor** [comment] 2018-08-15 13:47
I think I see what @jonjohnsonjr was getting at.

If you use per-domain credential helpers, then we expect them to be able to furnish a valid credential 100% of the time because it's been specified by domain.

For the global `credStore` path, this same property isn't true and we unconditionally configure a helper-based cred [here](https://github.com/google/go-containerregistry/blob/029d4b93c31fc9e5f7ab066313372c9be77af46b/pkg/authn/keychain.go#L128-L131).

What still puzzles me is that the helper [does have logic](https://github.com/google/go-containerregistry/blob/029d4b93c31fc9e5f7ab066313372c9be77af46b/pkg/authn/helper.go#L77-L82) to return an `Anonymous` credential and the only other non-error path requires that we've properly decoded a response [here](https://github.com/google/go-containerregistry/blob/029d4b93c31fc9e5f7ab066313372c9be77af46b/pkg/authn/helper.go#L94-L95).

I'd love to know what [this](https://github.com/google/go-containerregistry/blob/029d4b93c31fc9e5f7ab066313372c9be77af46b/pkg/authn/helper.go#L66) returns in the case of the `osxkeychain` with GCR.

I think it would be:
```shell
echo -n https://gcr.io | docker-credential-osx get
```

**Comment by markusthoemmes** [comment] 2018-08-15 14:10
@mattmoor the output of that command is:

```bash
$ echo -n https://gcr.io | docker-credential-osxkeychain get
credentials not found in native keychain
```

**Closed** 2018-08-15 14:25 UTC
