### ISSUE TITLE
removing redundancy in v1 layout?

### ISSUE THREAD

**Issue by deitch** [google/go-containerregistry#786] opened 2020-10-15 11:23 UTC
I really like the v1 layout. It follows (fairly closely) how containerd lays things out (at least as far as blobs are concerned) and it easy to understand.

My only concern with it is the deduplication around: downloads and storage.

Here is an example. I have two images, each with 10 layers, and they share all except for one layer (in addition, of course, to the manifest, index and config).

* With both images stored, I will have copies of everything, since each image has its own `blobs/` directory. 
* If I have the first image, and then download the second, I will redownload everything, since each image has its own `blobs/` directory

I have been thinking about how to resolve this. I see a few ways; would like some input on them and some other ideas. All of the options come down to a shared `blobs/` directory.

* provide `BlobsDir` option when pulling; this might break the official v1-layout format, but go-containerregistry would understand it
* similar to the first, but symlink `blobs/` on each image, so that it complies with the image layout spec, and thus other tools know how to use it

As an example, if I have two images in two subdirectories of my current directory, I might see something like this (annotated to show the symlinks):

```
$ find . -type f
./blobs
./blobs/sha256
./blobs/sha256/3588d02542238316759cbf24502f4344ffcc8a60c803870022f335d1390c13b4
./blobs/sha256/4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
./blobs/sha256/7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768
./image1/index.json
./image1/oci-layout
./image1/blobs -> ../blobs
./image2/index.json
./image2/oci-layout
./image2/blobs -> ../blobs
```

I would not make this a requirement, just an option. Without the option, all downloads look the original way:

```
$ find . -type f
./index.json
./oci-layout
./blobs/sha256/3588d02542238316759cbf24502f4344ffcc8a60c803870022f335d1390c13b4
./blobs/sha256/4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
./blobs/sha256/7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768
```

But with the option, we would gain deduplication.

What would it take to implement? (yes, happy to consider doing a PR, _if_ it will get taken in)

* `BlobDir` option to pull
* set up a symlink if `BlobDir` provided and it is not there
* check each blob sha before downloading - this means checking for the file's existence and hashing it - and only downloading it it is not there

Looking forward to feedback on this.

**Comment by deitch** [comment] 2020-10-29 14:14
Looking for some feedback on this @jonjohnsonjr @ImJasonH ?

**Comment by deitch** [comment] 2020-11-01 09:30
> implemented something very similar for rules_docker

"rules_docker"? What is that?

> My first impression would be that doing some cleverness with symlinks and a separate cache structure would be the best approach, but I'm reluctant to suggest anything concrete without experimenting

If this were just a google/go-containerregistry thing, I would say to have an option to use a separate cache and be done. But because we are implementing the [ocispec](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) on this, I would think that we would want to ensure whatever we use is readable by other tools. Hence my suggestion for symlinks.

> without experimenting

If we can agree on the approach, I am willing to get it done and submit a PR. But obviously, I don't want to put in the work until we agree on the approach.

**Comment by deitch** [comment] 2020-11-01 09:32
Actually, now that I think about it, I am kind of surprised that this is the spec, as containerd definitively does not follow it. It has the `blobs/sha256/` structure (as well as its own `ingest/` in parallel, but that is internal), but no `index.json`. Rather, each index and manifest is a blob in `blobs/sha256/`, and there is a separate boltdb database that contains the mapping of "image+tag" -> root (manifest or index).

I get why it needs a database:

* multiple changes at the same time would not work well with a single file
* the `index.json` format doesn't quite work for the mapping of image+tag, although you could use annotations to get it there, but it would be messy
* you need to store other things (snapshots, containers, etc.)

Still and all, I am surprised that the actual on-disk image format from containerd isn't actually image-spec compliant.

**Comment by mattmoor** [comment] 2020-11-01 15:23
rules_docker intermediate form: https://github.com/bazelbuild/rules_docker/blob/master/intermediate-form.md

**Comment by deitch** [comment] 2020-11-03 19:11
I see not reason to keep this open. @jonjohnsonjr explained that it does the right thing if you use the API correctly, you can put multiple images in one image-layout spec directory. 

You basically need to (abbreviated):

```go
                                ii, err := desc.ImageIndex() // or just an Image
                                p, err := layout.FromPath(path)
                                if err != nil {
                                        p, err = layout.Write(path, empty.Index)
                                        // handle error
                                }
                                annotations := map[string]string{
                                        ocispecv1.AnnotationRefName: image,
                                }
                                err = p.AppendIndex(ii, layout.WithAnnotations(annotations))
                                // if you want to download just for some platforms, do this instead
                                err = p.AppendIndex(ii, layout.WithAnnotations(annotations), layout.WithPlatform(platform))
```

**Comment by jonjohnsonjr** [comment] 2020-11-26 17:34
Closing since I think we reached consensus that this is working as intended, but let me know if I misunderstood.

**Comment by deitch** [comment] 2020-11-26 17:35
Definitely. Thanks for clarification.

**Closed by jonjohnsonjr** 2020-11-26 17:34 UTC
