### ISSUE TITLE
Error: Put "https://registry.gitlab.com/v2/isard/[MASKED]/api/manifests/main": http: ContentLength=2626 with Body length 0

### ISSUE THREAD

**Issue by sim6** [google/go-containerregistry#1182] opened 2021-11-17 08:02 UTC
Hello,

Firstly, thanks for your work.

We are using `crane tag` at gitlab-ci for [IsardVDI](isardvdi.com) project:

https://gitlab.com/isard/isardvdi/-/blob/main/.gitlab-ci.yml#L179

Until yesterday it works but now is saying:

```
Error: Put "https://registry.gitlab.com/v2/isard/[MASKED]/api/manifests/main": http: ContentLength=2626 with Body length 0
```

https://gitlab.com/isard/isardvdi/-/jobs/1790813552

I see a new `crane:debug` image uploaded 11h ago at https://console.cloud.google.com/artifacts/docker/go-containerregistry/us/gcr.io/crane?pli=1

Can you help us to debug the problem?

**Comment by imjasonh** [comment] 2021-11-17 13:58
Duplicate of https://github.com/google/go-containerregistry/issues/1183, fix is on the way.

**Closed by imjasonh** 2021-11-17 13:58 UTC

**Comment by sim6** [comment] 2021-11-18 05:30
Thanks!
